### PR TITLE
Added support for version 0 (zero)

### PR DESCRIPTION
**Pull request by ruionwriting**

### CODE REVIEW

**Comment by p-meier** [comment]
Hi. Thanks for your PR. I have two questions...

- Why should the plugin support version zero? Don't you normally start with version 1?
- Why did you turn off lab-code-coverage on some lines?

I'm currently on a workshop for the next 10 days and won't have internet access. So my next reply will take a while...

**Comment by ruionwriting** [comment]
@p-meier. Thanks for your comments.

- Version zero because is a good practice to exercise version compatibility transitions during pilot stage for public APIs. Let's say v0 is alpha/beta and we launch 1 as release candidate and we allow also the pilot consumers to exercise their side actions/code changes during the initial test phase.
- I was expecting this comment about coverage. Tbh i could get any logic reason to lab to complain about it. May I need some help here.

**Comment by ruionwriting** [comment]
@p-meier any change that you'll accept this change?

**Comment by p-meier** [comment]
Hi. Yes there is a chance. Actually I am searching for a maintainer for the project as I do not have enough time anymore to do it.

Would you be interested in becoming the lead maintainer?

**Comment by p-meier** [comment]
I implemented it myself and fixed the issue with lab. Releasing a new version soon...

**Pull request closed without merging**
